# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# NaviDE: override upstream US layout with GB
input {
    kb_layout = gb
    sensitivity = -0.25 # range -1.0 to 1.0, 0 = default
    accel_profile = flat # disable pointer acceleration
}

# NaviDE: disable hardware cursors — required for flipped monitor (DP-2)
# to avoid a bugged cursor canvas
cursor {
    no_hardware_cursors = true
}

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`
